# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-master-docker:
  stage: build
  script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - docker build --pull -t "$DOCKER_REGISTRY_IMAGE" .
    - docker push "$DOCKER_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy:
  stage: deploy
  image: terafin/rancher-cli-k8s:latest
  script:
    - rancher login "$RANCHER_URL" --skip-verify --token "$RANCHER_BEARER_TOKEN" --context "$RANCHER_CONTEXT"
    - rancher kubectl --namespace="$RANCHER_NAMESPACE" patch deployment "$CI_PROJECT_NAME-bedroom" -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
    - rancher kubectl --namespace="$RANCHER_NAMESPACE" patch deployment "$CI_PROJECT_NAME-entrance" -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
    - rancher kubectl --namespace="$RANCHER_NAMESPACE" patch deployment "$CI_PROJECT_NAME-guest-bedroom" -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
    - rancher kubectl --namespace="$RANCHER_NAMESPACE" patch deployment "$CI_PROJECT_NAME-study" -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
    - rancher kubectl --namespace="$RANCHER_NAMESPACE" patch deployment "$CI_PROJECT_NAME-living-room" -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
                